
# R scripts on a remote machine

In this chapter, we'll show you how to run an R script on rice. This is useful if you want to use an R script to read and wrangle large data files. 

If you follow the steps in this chapter, you'll open up two command lines: the rice command line and your local command line. To distinguish between commands to give to rice and commands to give to your local computer, we'll use

`local% [command]` 

for local commands and 

`rice% [command]`

for rice commands. Note that your command line prompts will not actually say `local%` or `rice%`. If you want to copy-and-paste the commands, make sure not to copy `local%` or `rice%`.

## Setup

### Install XQuartz / MobaXterm

Eventually, you'll want to run RStudio on rice, but operate it from your own computer. To remotely operate applications that have a graphical user-interface, like RStudio, you'll need special display software, such as the X Window System (also called X11 or X).

__Mac__

If you have a Mac, install XQuartz to use X. You can check if you already have XQuartz by looking in _Applications / Utilities_ for XQuartz. 

If you don't already have XQuartz, download and install XQuartz from the [download site](https://www.xquartz.org/).

__Windows__

If you have a Windows machine, install [MobaXterm](https://mobaxterm.mobatek.net/). Stanford's FarmShare wiki has [additional instructions](https://web.stanford.edu/group/farmshare/cgi-bin/wiki/index.php/Mobaxterm) for using MobaXterm, which may be useful. 

### Install Kerberos

Logging into rice requies your SUNet password and two-step authentication. We'll show you how to simplify authentication by using Kerberos. 

Download and install Kerberos from [Stanford IT website](https://uit.stanford.edu/software/kerberos). You'll also need Kerberos for AFS, which allows you you to share files. 

### Create aliases

Now, we'll create aliases for logging into Kerberos and rice. From your terminal, run

`local% echo $SHELL`

Possible results include `/bin/zsh` for the Zsh shell and `/bin/bash` for the Bash shell. In the following, we'll assume that you are using the Zsh shell and edit .zshrc. If you are using the Bash shell, instead edit .bash_profile.

Aliases (for Zsh) live in your .zshrc file. You can edit this file from RStudio by running 

`usethis::edit_file("~/.zshrc")`

The `~` represents your home directory. `edit_file()` will then open your .zshrc file in a new RStudio tab. 

Now, add the following line to the alias section of your .zshrc file. We recommend listing your aliases in alphabetical order.

`alias k='kinit your_sunet_id'`

This creates an alias for logging into Kerberos. The `k` is for Kerberos.

Next, create an alias for logging into rice.

`alias xr='ssh -Y your_sunet_id@rice.stanford.edu'`

The `x` is for X, and the `r` is for rice.

Note that the exact names of these aliases aren't important. If you already had aliases named `k` and `xr`, you can name your new ones anything you want.

### Source .zshrc

In order for your changes to your .zshrc file to take effect, you need to source the file. Run

`local% source ~/.zshrc`

### Edit .ssh/config

Next, edit your .ssh/config file. You can edit it from RStudio by running 

`usethis::edit_file("~/.ssh/config")`

Then, copy-and-paste the following lines into your .ssh/config file

```
Host rice rice.stanford.edu rice?? rice??.stanford.edu
  GSSAPIDelegateCredentials yes
  GSSAPIAuthentication yes
  ControlMaster auto
  ControlPath ~/.ssh/%r@%h:%p
  ControlPersist yes
```

Without these changes, you would have to login and authenticate each time you wanted to use rice in a new window or carry out tasks like copying files over to rice.

### Log into rice

First, log into Kerberos from the command line by running

`local% k`

You'll be prompted for your SUNet password.

Now, log into rice by running

`local% xr` 

You'll be prompted to two-step authenticate. After you've authenticated, you should see a message telling you that you're logged into rice. If you see a message about a broken pipe, something went wrong. Try logging in again. 

If you've successfully logged into rice, you will now have access to the rice command line. Later on, you'll want to copy some files from your local computer to rice, and so will need access to your local command line. We recommend opening up a local command line tab (in Terminal, you can open a new tab with _Cmd + T_). Now, you can control rice from one tab and your local computer from the other.

### Install R packages

In order to run your script, you'll likely need some R packages. It's easiest to install R packages from RStudio, so we'll run RStudio on rice. 

To run RStudio on rice, run

`rice% module load rstudio`

Then, to use X to operate RStudio remotely, run

`rice% rstudio &`

Without the `&`, you won't be able to use the rice command line. The `&` allows RStudio to run in the background, freeing up the rice command line.

XQuartz / MobaXterm should open, and you should see the RStudio interface. Use this RStudio window to install any R packages required by your script. You'll probably need at least tidyverse. From the RStudio console, run

`install.packages("tidyverse")`

## Run scripts with Rscript

### `scp`

We'll now show you how to copy files from your local computer to rice, and then from rice back to your local computer. We'll use `scp` (secure copy) to copy files from and to rice. Here are some templates for `scp` commands.

__Copy a single file__

`scp copy_from_path copy_to_path`

__Copy multiple files__

You can copy multiple files by separating them with a space.

`scp copy_from_path_1 copy_from_path_2 copy_to_path`

__Copy the contents of a folder__

To copy the entire contents, including sub-folders, of a folder, use the `-r` option. The `r` stands for recursive.

`scp -r folder_path copy_to_path`

__Copy to rice from local computer__

`local% scp local_path your_sunet_id@rice.stanford.edu:path_on_rice`

__Copy from rice to local computer__

`local% scp your_sunet_id@rice.stanford.edu:path_on_rice local_path`

### Copy your script to rice

Now, you can copy your script and any additional files you need over to rice. It will likely be easiest to just copy over your entire project directory. Say your project directory is called `very-exciting-project`. The command to copy over from your local computer to rice would be

`local% scp -r very-exciting-project your_sunet_id@rice.stanford.edu`

This will copy over your entire project folder to your home directory on rice. If you want, you can use the command `mkdir` to create a new folder on rice.

`rice% mkdir a-new-folder`

Then, you can edit the file path to copy your files into this new folder. Remember to add a `:` after `rice.stanford.edu`.

`local% scp -r very-exciting-project your_sunet_id@rice.stanford.edu:a-new-folder`

If you didn't log into Kerberos first, you would have to enter your password on rice every time you use `scp` to copy to or from rice.

### Run your script

Now, you can run your R script on rice. From the rice command line, run

`rice% Rscript path_to_your_script`

Note that you can change directories on rice just as you would on your local computer. If you want to navigate into your project folder, for example, you can run

`rice% cd project_folder`

### Copy results from rice 

Your data (or whatever your script produced) now lives on rice. You need to copy the data back to your local computer. From your local command line, run

`local% scp your_sunet_id@rice.stanford.edu:path_on_rice local_path`

For example, say you want to copy the file `exciting_data.rds` back to our local computer. You would run

`local% scp your_sunet_id@rice.stanford.edu:very-exciting-project/data/exciting_data.rds very-exciting-project/data/`

